### ISSUE TITLE
Add a README.md so that people can more easily steal stuff from here :D

### ISSUE THREAD

**Issue by mauriciojost** [mebubo/dotfiles#2]

**Comment by mauriciojost** [comment]
For instance how do you start your environment for nix? Which commands? Where are stuff meant to be placed if I need to add something?

**Comment by mebubo** [comment]
This repo is a bit of a hybrid: it can be used as 

- a traditional dotfiles repo for non-nix use cases such as WSL1 (symlinks in $HOME pointing to a checkout of this repo)
- a standalone nix + home-manager on non-NixOS linux (symlink `.config/nixpkgs` to point to `.config/nixpkgs` from this repo and run `nix-shell -p home-manager-init --run "home-manager switch"`
- a full-blown NixOS config with system-wide home-manager (`nixos-rebuild boot -I nixos-config=nixos/devices/laptop/configuration.nix -I nixpkgs=channel:nixos-unstable`)

**Comment by mauriciojost** [comment]
Such explanation should do ;)
